import jsQR from 'jsqr';

window.BMH_QR_DECODE = function (imageData) {
  try {
    if (!imageData || !imageData.data || !imageData.width || !imageData.height) return '';
    const result = jsQR(imageData.data, imageData.width, imageData.height, { inversionAttempts: 'attemptBoth' });
    return String(result?.data || '').trim();
  } catch (e) {
    return '';
  }
};

(function installReceptionPatientBackgroundHydrator() {
  if (window.__bmhReceptionPatientBackgroundHydratorV3) return;
  window.__bmhReceptionPatientBackgroundHydratorV3 = true;

  const DB_NAME = 'bmh-reception-cache';
  const STORE = 'patients';
  const TWO_MONTHS_MS = 62 * 24 * 60 * 60 * 1000;
  const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
  const bmhNum = v => { const m = String(v || '').trim().match(/^BMSH-(\d{1,9})$/i); return m ? parseInt(m[1], 10) : 0; };
  const bmhId = v => { const d = String(v || '').replace(/\D/g, ''); return d ? 'BMSH-' + d.padStart(6, '0').slice(-6) : ''; };
  const phoneKey = v => { const d = String(v || '').replace(/\D/g, ''); return d.length >= 10 ? d.slice(-10) : d; };
  const stamp = p => String(p?.updatedAt || p?.lastUpdated || p?.registeredAt || p?.createdAt || p?.checkinAt || p?.queueDate || '');

  function openCache() { return new Promise((resolve, reject) => { if (!window.indexedDB) return reject(new Error('IndexedDB unavailable')); const req = indexedDB.open(DB_NAME, 1); req.onupgradeneeded = () => { const db = req.result; if (!db.objectStoreNames.contains(STORE)) db.createObjectStore(STORE, { keyPath: 'bmhId' }); }; req.onsuccess = () => resolve(req.result); req.onerror = () => reject(req.error || new Error('IndexedDB open failed')); }); }
  async function cachePutMany(patients) { if (!patients.length) return; try { const db = await openCache(); await new Promise((resolve, reject) => { const tx = db.transaction(STORE, 'readwrite'), store = tx.objectStore(STORE); patients.forEach(p => { if (p?.bmhId) store.put(p); }); tx.oncomplete = resolve; tx.onerror = () => reject(tx.error || new Error('IndexedDB write failed')); }); db.close(); } catch (e) { console.warn('Reception patient cache write skipped', e); } }
  async function cacheReadAll() { try { const db = await openCache(); const rows = await new Promise((resolve, reject) => { const tx = db.transaction(STORE, 'readonly'), req = tx.objectStore(STORE).getAll(); req.onsuccess = () => resolve(req.result || []); req.onerror = () => reject(req.error || new Error('IndexedDB read failed')); }); db.close(); return rows; } catch (_) { return []; } }

  function normalize(row, key) { const p = Object.assign({}, row || {}, { bmhId: row?.bmhId || key }); return typeof window.normalizePatientRecord === 'function' ? window.normalizePatientRecord(p) : p; }
  function upsertPatient(row, key) { if (!row || typeof row !== 'object') return null; const p = normalize(row, key); if (!p.bmhId) return null; if (!Array.isArray(window.PATIENTS)) window.PATIENTS = []; const id = String(p.bmhId || '').trim().toUpperCase(); const idx = window.PATIENTS.findIndex(x => String(x?.bmhId || '').trim().toUpperCase() === id); if (idx >= 0) window.PATIENTS[idx] = Object.assign({}, window.PATIENTS[idx], p); else window.PATIENTS.push(p); const n = bmhNum(p.bmhId); if (n > 0) { window._nextPatientNum = Math.max(Number(window._nextPatientNum || 0), n + 1); try { localStorage.setItem('bmh_last_patient_num', String(n)); } catch (_) {} } return p; }
  function allPatients() { return Array.isArray(window.PATIENTS) ? window.PATIENTS : []; }
  function nameOf(p) { return p?.name || [p?.firstName || p?.fn, p?.lastName || p?.ln].filter(Boolean).join(' ') || 'Patient'; }
  function phonesOf(p) { return [p?.mob, p?.mobile, p?.phone, p?.mob2, p?.altMobile].map(phoneKey).filter(Boolean); }

  function setFollowUp() { const sel = document.getElementById('rc-purpose'); if (!sel) return; const opt = Array.from(sel.options || []).find(o => /follow/i.test(o.value || o.textContent || '')); if (opt) { sel.value = opt.value || opt.textContent; sel.dispatchEvent(new Event('change', { bubbles: true })); } }
  function setVal(id, value) { const el = document.getElementById(id); if (el && value != null && value !== '') { el.value = value; el.dispatchEvent(new Event('input', { bubbles: true })); el.dispatchEvent(new Event('change', { bubbles: true })); } }
  function prefillPatient(id) { const key = String(id || '').trim().toUpperCase(); const p = allPatients().find(x => String(x?.bmhId || '').trim().toUpperCase() === key); if (!p) return; const parts = String(nameOf(p)).trim().split(/\s+/); setVal('rc-fn', p.firstName || p.fn || parts.shift() || ''); setVal('rc-ln', p.lastName || p.ln || parts.join(' ') || ''); setVal('rc-rel', p.rel || p.relative || p.fatherName || ''); setVal('rc-dob', p.dob || ''); setVal('rc-age', p.age || ''); setVal('rc-sex', p.sex || 'Male'); setVal('rc-mob-inp', p.mob || p.mobile || ''); setVal('rc-mob2', p.mob2 || p.altMobile || ''); setVal('rc-email', p.email || ''); setVal('rc-addr', p.addr || p.address || ''); setVal('rc-dept', p.dept || 'ophtho'); setVal('rc-centre', p.centre || document.getElementById('rc-centre')?.value || 'CHD'); const uid = document.getElementById('rc-uid'); if (uid) uid.textContent = p.bmhId; const badge = document.getElementById('rc-prefill-badge'); if (badge) badge.style.display = 'block'; setFollowUp(); window.showToast?.('Existing patient details loaded', 's'); }

  function renderBmshMatches(matches) { const box = document.getElementById('rc-bmhid-result'); if (!box) return; if (!matches.length) { box.innerHTML = '<div style="font-size:11px;color:var(--g2);padding:6px 8px">No matching patient found yet. Cache is still hydrating.</div>'; return; } box.innerHTML = matches.slice(0, 12).map(p => '<div onclick="window.bmhReceptionPrefillPatient(\'' + String(p.bmhId).replace(/'/g, '') + '\')" style="cursor:pointer;background:#fff;border:1px solid var(--g4);border-radius:8px;padding:8px 10px;margin-bottom:5px;font-size:12px"><b>' + nameOf(p) + '</b><div style="font-family:var(--mono);color:var(--blue)">' + p.bmhId + '</div><div style="color:var(--g1)">' + (p.mob || p.mobile || '') + ' · ' + (p.age || '') + '/' + (p.sex || '') + '</div></div>').join(''); }
  function renderPhoneMatches(matches) { const wrap = document.getElementById('rc-phone-results'), list = document.getElementById('rc-phone-matches-list'); if (!wrap || !list) return; if (!matches.length) { wrap.style.display = 'none'; list.innerHTML = ''; return; } wrap.style.display = 'block'; list.innerHTML = matches.slice(0, 12).map(p => '<div onclick="window.bmhReceptionPrefillPatient(\'' + String(p.bmhId).replace(/'/g, '') + '\')" style="cursor:pointer;padding:8px 10px;border-bottom:1px solid var(--g5);font-size:12px"><b>' + nameOf(p) + '</b><div style="font-family:var(--mono);color:var(--blue)">' + p.bmhId + '</div><div style="color:var(--g1)">' + (p.mob || p.mobile || '') + ' · ' + (p.age || '') + '/' + (p.sex || '') + '</div></div>').join(''); }

  async function fetchDirectBmsh(id) { if (!window.FBDB || !id) return null; try { const snap = await window.FBDB.ref('patients/' + id).once('value'); const p = snap && snap.val ? upsertPatient(snap.val(), id) : null; if (p) await cachePutMany([p]); return p; } catch (_) { return null; } }
  async function lookupBmsh(raw) { const digits = String(raw || '').replace(/\D/g, ''); if (digits.length < 4) { renderBmshMatches([]); return []; } const exact = digits.length >= 6 ? bmhId(digits.slice(0, 6)) : ''; if (exact) { let p = allPatients().find(x => String(x?.bmhId || '').toUpperCase() === exact); if (!p) p = await fetchDirectBmsh(exact); const m = p ? [p] : []; renderBmshMatches(m); return m; } const pref = 'BMSH-' + digits; const m = allPatients().filter(p => String(p?.bmhId || '').toUpperCase().startsWith(pref)).sort((a, b) => bmhNum(b.bmhId) - bmhNum(a.bmhId)).slice(0, 12); renderBmshMatches(m); return m; }
  function lookupPhone(raw) { const q = phoneKey(raw); if (q.length < 5) { renderPhoneMatches([]); return []; } const m = allPatients().filter(p => phonesOf(p).some(ph => ph.startsWith(q))).sort((a, b) => bmhNum(b.bmhId) - bmhNum(a.bmhId)).slice(0, 12); renderPhoneMatches(m); return m; }

  window.bmhReceptionPrefillPatient = prefillPatient;
  window.bmhReceptionLookupBmshCache = lookupBmsh;
  window.bmhReceptionLookupPhoneCache = lookupPhone;

  function wrapLookupInputs() { if (window.__bmhReceptionLookupBridgeInstalled) return; const b = document.getElementById('rc-bmhid-search'), m = document.getElementById('rc-mob-inp'); if (!b && !m) return; window.__bmhReceptionLookupBridgeInstalled = true; if (b) b.addEventListener('input', () => lookupBmsh(b.value)); if (m) m.addEventListener('input', () => lookupPhone(m.value)); }
  function refreshReceptionSearchUi() { try { window.dispatchEvent(new CustomEvent('bmh:patientsUpdated')); } catch (_) {} try { if (typeof window.genRcUID === 'function') window.genRcUID(); } catch (_) {} try { const b = document.getElementById('rc-bmhid-search'); if (b?.value) lookupBmsh(b.value); } catch (_) {} try { const m = document.getElementById('rc-mob-inp'); if (m?.value) lookupPhone(m.value); } catch (_) {} try { const q = document.getElementById('rc-search-inp'); if (q?.value && typeof window.filterRcExist === 'function') window.filterRcExist(q.value); } catch (_) {} }

  async function feedRows(rows, opts = {}) { const chunk = opts.chunk || 20, gap = opts.gap || 260, cacheRows = []; for (let i = 0; i < rows.length; i += chunk) { rows.slice(i, i + chunk).forEach(item => { const p = upsertPatient(item.row || item, item.key || item.bmhId); if (p) cacheRows.push(p); }); refreshReceptionSearchUi(); await sleep(gap); } await cachePutMany(cacheRows); refreshReceptionSearchUi(); }
  async function replayLocalCache() { const cached = await cacheReadAll(); if (!cached.length) return; cached.sort((a, b) => bmhNum(b.bmhId) - bmhNum(a.bmhId)); window.__bmhReceptionLocalCacheCount = cached.length; await feedRows(cached, { chunk: 35, gap: 80 }); }
  function mergeSnapshot(map, snap) { const data = snap && snap.val ? (snap.val() || {}) : {}; Object.keys(data).forEach(key => { const p = normalize(data[key], key); if (p?.bmhId) map.set(String(p.bmhId).trim().toUpperCase(), { key, row: p }); }); }
  async function fetchRecentTwoMonths() { if (!window.FBDB) return []; const since = new Date(Date.now() - TWO_MONTHS_MS).toISOString(), map = new Map(); const reads = [() => window.FBDB.ref('patients').orderByKey().limitToLast(1000).once('value'), () => window.FBDB.ref('patients').orderByChild('createdAt').startAt(since).limitToFirst(1200).once('value'), () => window.FBDB.ref('patients').orderByChild('registeredAt').startAt(since).limitToFirst(1200).once('value'), () => window.FBDB.ref('patients').orderByChild('updatedAt').startAt(since).limitToFirst(900).once('value'), () => window.FBDB.ref('patients').orderByChild('checkinAt').startAt(since).limitToFirst(900).once('value'), () => window.FBDB.ref('patients').orderByChild('queueDate').startAt(since).limitToFirst(900).once('value')]; for (const read of reads) { try { mergeSnapshot(map, await read()); } catch (_) {} await sleep(700); } return Array.from(map.values()).sort((a, b) => { const an = bmhNum(a.row?.bmhId || a.key), bn = bmhNum(b.row?.bmhId || b.key); if (an || bn) return bn - an; return String(stamp(b.row)).localeCompare(String(stamp(a.row))); }); }
  async function hydratePatients() { if (window.__bmhReceptionHydratingPatients || !window.FBDB) return; window.__bmhReceptionHydratingPatients = true; try { await replayLocalCache(); await sleep(500); const recent = await fetchRecentTwoMonths(); window.__bmhReceptionHydratedPatientCount = recent.length; await feedRows(recent, { chunk: 20, gap: 300 }); } catch (e) { console.warn('Reception background patient hydration failed', e); } finally { window.__bmhReceptionHydratingPatients = false; } }
  function scheduleHydration() { wrapLookupInputs(); if (!window.FBDB) { setTimeout(scheduleHydration, 500); return; } setTimeout(hydratePatients, 700); }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', scheduleHydration); else scheduleHydration(); setTimeout(wrapLookupInputs, 1000); setTimeout(wrapLookupInputs, 3000); window.addEventListener('bmh:receptionOpened', hydratePatients);
})();
