import jsQR from 'jsqr';

window.BMH_QR_DECODE = function (imageData) {
  try {
    if (!imageData || !imageData.data || !imageData.width || !imageData.height) return '';
    const result = jsQR(imageData.data, imageData.width, imageData.height, { inversionAttempts: 'attemptBoth' });
    return String(result?.data || '').trim();
  } catch (e) { return ''; }
};

(function () {
  if (window.__bmhReceptionPatientBackgroundHydratorV4) return;
  window.__bmhReceptionPatientBackgroundHydratorV4 = true;
  const DB = 'bmh-reception-cache', STORE = 'patients', TWO_MONTHS = 62 * 86400000;
  const sleep = ms => new Promise(r => setTimeout(r, ms));
  const bnum = v => { const m = String(v || '').match(/^BMSH-(\d{1,9})$/i); return m ? +m[1] : 0; };
  const bid = v => { const d = String(v || '').replace(/\D/g, ''); return d ? 'BMSH-' + d.padStart(6, '0').slice(-6) : ''; };
  const phone = v => { const d = String(v || '').replace(/\D/g, ''); return d.length >= 10 ? d.slice(-10) : d; };
  const patients = () => Array.isArray(window.PATIENTS) ? window.PATIENTS : (window.PATIENTS = []);
  const pname = p => p?.name || [p?.firstName || p?.fn, p?.lastName || p?.ln].filter(Boolean).join(' ') || 'Patient';
  const pphones = p => [p?.mob, p?.mobile, p?.phone, p?.mob2, p?.altMobile].map(phone).filter(Boolean);

  function openDb() { return new Promise((ok, fail) => { if (!indexedDB) return fail(new Error('No IndexedDB')); const r = indexedDB.open(DB, 1); r.onupgradeneeded = () => { const db = r.result; if (!db.objectStoreNames.contains(STORE)) db.createObjectStore(STORE, { keyPath: 'bmhId' }); }; r.onsuccess = () => ok(r.result); r.onerror = () => fail(r.error); }); }
  async function readCache() { try { const db = await openDb(); const rows = await new Promise((ok, fail) => { const tx = db.transaction(STORE), req = tx.objectStore(STORE).getAll(); req.onsuccess = () => ok(req.result || []); req.onerror = () => fail(req.error); }); db.close(); return rows; } catch (_) { return []; } }
  async function writeCache(rows) { if (!rows.length) return; try { const db = await openDb(); await new Promise((ok, fail) => { const tx = db.transaction(STORE, 'readwrite'), st = tx.objectStore(STORE); rows.forEach(p => p?.bmhId && st.put(p)); tx.oncomplete = ok; tx.onerror = () => fail(tx.error); }); db.close(); } catch (e) { console.warn('Reception patient cache write skipped', e); } }
  function norm(row, key) { const p = Object.assign({}, row || {}, { bmhId: row?.bmhId || key }); return typeof window.normalizePatientRecord === 'function' ? window.normalizePatientRecord(p) : p; }
  function upsert(row, key) { const p = norm(row, key); if (!p?.bmhId) return null; const list = patients(), id = String(p.bmhId).toUpperCase(); const i = list.findIndex(x => String(x?.bmhId || '').toUpperCase() === id); if (i >= 0) list[i] = Object.assign({}, list[i], p); else list.push(p); const n = bnum(p.bmhId); if (n > 0) { window._nextPatientNum = Math.max(+window._nextPatientNum || 0, n + 1); try { localStorage.setItem('bmh_last_patient_num', String(n)); } catch (_) {} } return p; }
  function refresh() { try { window.dispatchEvent(new CustomEvent('bmh:patientsUpdated')); } catch (_) {} try { if (typeof window.genRcUID === 'function') window.genRcUID(); } catch (_) {} const b = document.getElementById('rc-bmhid-search'); if (b?.value) lookupBmsh(b.value); const m = document.getElementById('rc-mob-inp'); if (m?.value) lookupPhone(m.value); }
  async function feed(rows, chunk = 20, gap = 300) { const saved = []; for (let i = 0; i < rows.length; i += chunk) { rows.slice(i, i + chunk).forEach(x => { const p = upsert(x.row || x, x.key || x.bmhId); if (p) saved.push(p); }); refresh(); await sleep(gap); } await writeCache(saved); refresh(); }
  function merge(map, snap) { const data = snap?.val?.() || {}; Object.keys(data).forEach(key => { const p = norm(data[key], key); if (p?.bmhId) map.set(String(p.bmhId).toUpperCase(), { key, row: p }); }); }
  async function hydrate() { if (window.__bmhReceptionHydratingPatients || !window.FBDB) return; window.__bmhReceptionHydratingPatients = true; try { const cached = await readCache(); cached.sort((a, b) => bnum(b.bmhId) - bnum(a.bmhId)); await feed(cached, 35, 80); const since = new Date(Date.now() - TWO_MONTHS).toISOString(), map = new Map(); const reads = [() => window.FBDB.ref('patients').orderByKey().limitToLast(1000).once('value'), () => window.FBDB.ref('patients').orderByChild('createdAt').startAt(since).limitToFirst(1200).once('value'), () => window.FBDB.ref('patients').orderByChild('registeredAt').startAt(since).limitToFirst(1200).once('value'), () => window.FBDB.ref('patients').orderByChild('updatedAt').startAt(since).limitToFirst(900).once('value'), () => window.FBDB.ref('patients').orderByChild('checkinAt').startAt(since).limitToFirst(900).once('value'), () => window.FBDB.ref('patients').orderByChild('queueDate').startAt(since).limitToFirst(900).once('value')]; for (const r of reads) { try { merge(map, await r()); } catch (_) {} await sleep(700); } const rows = Array.from(map.values()).sort((a, b) => bnum(b.row?.bmhId || b.key) - bnum(a.row?.bmhId || a.key)); window.__bmhReceptionHydratedPatientCount = rows.length; await feed(rows, 20, 300); } catch (e) { console.warn('Reception background patient hydration failed', e); } finally { window.__bmhReceptionHydratingPatients = false; } }

  function followup() { const s = document.getElementById('rc-purpose'); if (!s) return; const o = Array.from(s.options || []).find(x => /follow/i.test(x.value || x.textContent || '')); if (o) { s.value = o.value || o.textContent; s.dispatchEvent(new Event('change', { bubbles: true })); } }
  function val(id, v) { const el = document.getElementById(id); if (el && v != null && v !== '') { el.value = v; el.dispatchEvent(new Event('input', { bubbles: true })); el.dispatchEvent(new Event('change', { bubbles: true })); } }
  function clearPanels() { const a = document.getElementById('rc-bmhid-result'); if (a) a.innerHTML = ''; const s = document.getElementById('rc-bmhid-search'); if (s) s.value = ''; const pr = document.getElementById('rc-phone-results'); if (pr) pr.style.display = 'none'; ['rc-phone-matches-list', 'rc-phone-match'].forEach(id => { const el = document.getElementById(id); if (el) el.innerHTML = ''; }); }
  function resetForm() { ['rc-fn','rc-ln','rc-rel','rc-dob','rc-age','rc-mob-inp','rc-mob2','rc-email','rc-addr','rc-advance-amt','rc-advance-purpose','rc-ins-name','rc-policy','rc-claim-amt','rc-ref-name','rc-ref-mobile','rc-refund-amt','rc-refund-reason'].forEach(id => { const el = document.getElementById(id); if (el) { el.value = id === 'rc-advance-amt' ? '0' : ''; el.dispatchEvent(new Event('input', { bubbles: true })); el.dispatchEvent(new Event('change', { bubbles: true })); } }); ['rc-no-fee','rc-force-new-bmsh'].forEach(id => { const el = document.getElementById(id); if (el) { el.checked = false; el.dispatchEvent(new Event('change', { bubbles: true })); } }); const pur = document.getElementById('rc-purpose'); if (pur) { pur.value = 'New Consultation'; pur.dispatchEvent(new Event('change', { bubbles: true })); } const sex = document.getElementById('rc-sex'); if (sex) sex.value = 'Male'; const badge = document.getElementById('rc-prefill-badge'); if (badge) badge.style.display = 'none'; clearPanels(); try { if (typeof window.genRcUID === 'function') window.genRcUID(); } catch (_) {} }
  function prefill(id) { const key = String(id || '').toUpperCase(); const p = patients().find(x => String(x?.bmhId || '').toUpperCase() === key); if (!p) return; const parts = String(pname(p)).trim().split(/\s+/); val('rc-fn', p.firstName || p.fn || parts.shift() || ''); val('rc-ln', p.lastName || p.ln || parts.join(' ') || ''); val('rc-rel', p.rel || p.relative || p.fatherName || ''); val('rc-dob', p.dob || ''); val('rc-age', p.age || ''); val('rc-sex', p.sex || 'Male'); val('rc-mob-inp', p.mob || p.mobile || ''); val('rc-mob2', p.mob2 || p.altMobile || ''); val('rc-email', p.email || ''); val('rc-addr', p.addr || p.address || ''); val('rc-dept', p.dept || 'ophtho'); val('rc-centre', p.centre || document.getElementById('rc-centre')?.value || 'CHD'); const uid = document.getElementById('rc-uid'); if (uid) uid.textContent = p.bmhId; const badge = document.getElementById('rc-prefill-badge'); if (badge) badge.style.display = 'block'; followup(); clearPanels(); window.showToast?.('Existing patient details loaded', 's'); }
  function card(p) { const id = String(p.bmhId || '').replace(/'/g, ''); return '<div onclick="window.bmhReceptionPrefillPatient(\'' + id + '\')" style="cursor:pointer;background:#fff;border:1px solid var(--g4);border-radius:8px;padding:8px 10px;margin-bottom:5px;font-size:12px"><b>' + pname(p) + '</b><div style="font-family:var(--mono);color:var(--blue)">' + p.bmhId + '</div><div style="color:var(--g1)">' + (p.mob || p.mobile || '') + ' · ' + (p.age || '') + '/' + (p.sex || '') + '</div></div>'; }
  function renderBmsh(list) { const box = document.getElementById('rc-bmhid-result'); if (box) box.innerHTML = list.length ? list.slice(0, 12).map(card).join('') : '<div style="font-size:11px;color:var(--g2);padding:6px 8px">No matching patient found yet. Cache is still hydrating.</div>'; }
  function renderPhone(list) { const wrap = document.getElementById('rc-phone-results'), listEl = document.getElementById('rc-phone-matches-list'); if (!wrap || !listEl) return; if (!list.length) { wrap.style.display = 'none'; listEl.innerHTML = ''; return; } wrap.style.display = 'block'; listEl.innerHTML = list.slice(0, 12).map(card).join(''); }
  async function direct(id) { if (!window.FBDB || !id) return null; try { const s = await window.FBDB.ref('patients/' + id).once('value'); const p = s?.val ? upsert(s.val(), id) : null; if (p) await writeCache([p]); return p; } catch (_) { return null; } }
  async function lookupBmsh(raw) { const d = String(raw || '').replace(/\D/g, ''); if (d.length < 4) return renderBmsh([]); if (d.length >= 6) { const id = bid(d.slice(0, 6)); let p = patients().find(x => String(x?.bmhId || '').toUpperCase() === id); if (!p) p = await direct(id); return renderBmsh(p ? [p] : []); } const pref = 'BMSH-' + d; renderBmsh(patients().filter(p => String(p?.bmhId || '').toUpperCase().startsWith(pref)).sort((a, b) => bnum(b.bmhId) - bnum(a.bmhId))); }
  function lookupPhone(raw) { const q = phone(raw); if (q.length < 5) return renderPhone([]); renderPhone(patients().filter(p => pphones(p).some(x => x.startsWith(q))).sort((a, b) => bnum(b.bmhId) - bnum(a.bmhId))); }
  window.bmhReceptionPrefillPatient = prefill; window.bmhReceptionLookupBmshCache = lookupBmsh; window.bmhReceptionLookupPhoneCache = lookupPhone;
  function wire() { const b = document.getElementById('rc-bmhid-search'), m = document.getElementById('rc-mob-inp'); if (b && !b.__bmhLookupWired) { b.__bmhLookupWired = true; b.addEventListener('input', () => lookupBmsh(b.value)); } if (m && !m.__bmhLookupWired) { m.__bmhLookupWired = true; m.addEventListener('input', () => lookupPhone(m.value)); } if (!window.__bmhRegisterResetWired && typeof window.registerPatient === 'function') { window.__bmhRegisterResetWired = true; const old = window.registerPatient; window.registerPatient = async function () { const uid = String(document.getElementById('rc-uid')?.textContent || '').trim(); const result = await old.apply(this, arguments); setTimeout(() => { const saved = result || (uid && patients().some(p => String(p?.bmhId || '').trim() === uid)); if (saved) resetForm(); }, 600); return result; }; } }
  function start() { wire(); if (!window.FBDB) return setTimeout(start, 500); setTimeout(hydrate, 700); }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', start); else start(); setTimeout(wire, 1000); setTimeout(wire, 3000); window.addEventListener('bmh:receptionOpened', hydrate);
})();
